---
- name: Base system + storage + NVIDIA
  hosts: debian
  become: yes
  become_method: sudo

  roles:
    - ssh
    - base
    - storage
    - swap
    - zram
    - nvidia

- name: AI services
  hosts: debian
  become: yes
  become_method: sudo

  roles:
    - ollama
    - samba
    - backup
