- name: Remove UFW rule for Ollama port
  community.general.ufw:
    rule: deny
    port: "11434"
    proto: tcp
    from_ip: "192.168.0.0/16"

- name: Stop Ollama container
  community.docker.docker_container:
    name: ollama
    state: stopped
    force_kill: true

- name: Remove Ollama container
  community.docker.docker_container:
    name: ollama
    state: absent

- name: Remove Ollama image
  community.docker.docker_image:
    name: ollama/ollama
    state: absent
    force_absent: true

- name: Remove Ollama volume
  community.docker.docker_volume:
    name: ollama_data
    state: absent