- name: Update apt cache
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name:
      - sudo
      - vim
      - curl
      - git
      - htop
      - rsync
      - borgbackup
    state: present

- name: Create shared group
  group:
    name: shared
    state: present

- name: Create users
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    create_home: yes
  loop: "{{ users }}"

- name: Add users to shared group
  user:
    name: "{{ item.name }}"
    groups: shared
    append: yes
  loop: "{{ users }}"
