- name: Remove users from shared group
  user:
    name: "{{ item.name }}"
    groups: ""
    state: present
  loop: "{{ users_to_remove }}"

- name: Remove users
  user:
    name: "{{ item.name }}"
    state: absent
    remove: yes
  loop: "{{ users_to_remove }}"

- name: Remove shared group
  group:
    name: shared
    state: absent

- name: Remove packages (SAFE VERSION)
  apt:
    name:
      - borgbackup
      - rsync
      - htop
      - curl
    state: absent
    autoremove: yes

- name: Clean apt cache
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
