- name: Remove borg repositories per user
  file:
    path: "/srv/backups/{{ item.name }}"
    state: absent
  loop: "{{ users }}"

- name: Remove /srv/backups directory
  file:
    path: /srv/backups
    state: absent

- name: Remove shared directory
  file:
    path: /srv/shared
    state: absent

- name: Remove users from shared group
  user:
    name: "{{ item.name }}"
    groups: ""
    state: present
  loop: "{{ users_to_remove }}"

- name: Remove shared group
  group:
    name: shared
    state: absent
